# SPDX-License-Identifier: GPL-2.0
# dtb-$(CONFIG_SOC_EXYNOS9830) += \
#	exynos9830-smdk9830.dtbo \
#	exynos9830-smdk9830_r01.dtbo \
#	exynos9830-universal9830.dtbo \
#	exynos9830-universal9830_r01.dtbo \
#	exynos9830-universal9830_system_as_root.dtbo

# always	:= $(dtb-y) $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
