# SPDX-License-Identifier: GPL-2.0
#dtb-$(CONFIG_SOC_EXYNOS9820) += \
#	exynos9820-smdk9820.dtbo \
#	exynos9820-universal9820_rev5.dtbo \
#	exynos9820-universal9820_revC01.dtbo \
#	exynos9820-universal9820_revC03.dtbo \
#	exynos9820-universal9820_revC04.dtbo \
#	exynos9820-universal9820_revC06.dtbo \
#	exynos9820-universal9820_5g.dtbo \
#	exynos9820-universal9820_s5100_rev1.dtbo

# always		:= $(dtb-y) $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
