obj-$(CONFIG_BATTERY_SAMSUNG)	+= sec_battery.o sec_battery_sysfs.o sec_battery_dt.o
obj-$(CONFIG_OF)		+= sec_adc.o
obj-$(CONFIG_BATTERY_CISD)	+= sec_cisd.o
obj-$(CONFIG_MULTI_CHARGING)	+= sec_multi_charger.o
obj-$(CONFIG_STEP_CHARGING)	+= sec_step_charging.o
obj-$(CONFIG_WIRELESS_AUTH)	+= sec_battery_misc.o
obj-$(CONFIG_DIRECT_CHARGING)	+= sec_direct_charger.o
obj-$(CONFIG_UPDATE_BATTERY_DATA)	+= sec_battery_data.o
obj-$(CONFIG_BATTERY_NOTIFIER)	+= battery_notifier.o

# fuelgauge
obj-$(CONFIG_FUELGAUGE_MAX77705)	+= max77705_fuelgauge.o

# charger
obj-$(CONFIG_CHARGER_MAX77705)	+= max77705_charger.o

# mfc charger
obj-$(CONFIG_WIRELESS_CHARGER_MFC)	+= mfc_charger.o
obj-$(CONFIG_WIRELESS_CHARGER_MFC_S2MIW04)	+= mfc_s2miw04_charger.o

# direct charger
obj-$(CONFIG_CHARGER_PCA9468)	+= pca9468_charger.o

# voltage divider
obj-$(CONFIG_VDIVIDER_BC80)	+= bc80_vdivider.o
